### ISSUE TITLE
Create Ruby script to obtain bibliographic data from Project PLATEAU site

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-plateau#1]
The Project PLATEAU site is here:
* https://www.mlit.go.jp/plateau/libraries

There are 2 types of documents we need to obtain the bibliographic data from.
* Handbook and Handbook Annex
* Technical reports

## Handbook

https://www.mlit.go.jp/plateau/libraries/handbooks/

These are the data that we need:
<img width="1232" alt="Screenshot 2024-07-06 at 4 59 12 PM" src="https://github.com/relaton/relaton-data-plateau/assets/11865/6db3f34a-8e9f-49a9-b9d9-bb0dfa305cae">

There is a special kind of Handbook that is a Handbook Annex, it is identified by the document ID and the title:
<img width="629" alt="Screenshot 2024-07-06 at 5 01 14 PM" src="https://github.com/relaton/relaton-data-plateau/assets/11865/785c0f92-0f92-4dfe-909c-a57be20f6c58">

## Technical report

https://www.mlit.go.jp/plateau/libraries/technical-reports/

This is a paginated section so we need to scrape all pages.

There are two types of technical reports.
* Use case
* Data

This is the data that we need:

Use case:
<img width="1218" alt="Screenshot 2024-07-06 at 5 02 32 PM" src="https://github.com/relaton/relaton-data-plateau/assets/11865/57b138b3-e822-4a79-92e0-1b97093c94a9">

Data:
<img width="807" alt="Screenshot 2024-07-06 at 5 03 45 PM" src="https://github.com/relaton/relaton-data-plateau/assets/11865/014ba3a1-4a78-4f0b-8148-e0915aa2c905">

## Summary

We need a Ruby script that when run, fetches all this information and stores it in a YAML file.

**Comment by H3xano** [comment]
Hi, I have written the demanded script. It fetches all the necessary information and stores it in two separate YAML files (handbooks.yaml and technical-reports.yaml). It performs the job in an efficient manner (it only send two HTTP requests to get all the data).  did I miss any requirement so far ?

**Comment by ronaldtse** [comment]
@H3xano thank you for the contribution, they have been merged in relaton/relaton-plateau#1
